name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clone submodules as standard repositories
      # `git submodule update --init --recursive` doesn't work.
      run: git clone http://github.com/MuAlphaOmegaEpsilon/cmake
    - name: Build and test
      run: ctest --build-and-test . build --parallel --build-generator "Unix Makefiles" --test-command ctest
