name: Build and test

on: [push]
paths: .github/workflows/*
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - name: Install prettier
        run: cd .github/workflows/ && npm install prettier
      - name: Run prettier
        run: prettier *.yml --list-different
